---
title: "ImportData"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("here")
library("googledrive")
library("googlesheets4")
```


```{r}
googledrive::drive_auth()
gs4_auth(token = drive_token())


#d2017_autumn <- googledrive::drive_get("2017_autumn")
# Copio el id (boton derecho )


# List files 
fs <- drive_ls(
  path=as_id("https://drive.google.com/drive/folders/13y6oHuJ0KuovdP0z9dfpLlugcr6zdlV-?usp=sharings"), 
  type = "spreadsheet",
  pattern = "20") 

readReplicas <- function(id){
  require(dplyr)
  require(googlesheets4)
  
  r1 <- read_sheet(ss=id, sheet = 'R1', na = "NA")
  r2 <- read_sheet(ss=id, sheet = 'R2', na = "NA")
  r3 <- read_sheet(ss=id, sheet = 'R3', na = "NA")
  r4 <- read_sheet(ss=id, sheet = 'R4', na = "NA")
  r5 <- read_sheet(ss=id, sheet = 'R5', na = "NA")
  d <- rbind(r1,r2,r3,r4,r5)
  return(d)
} 

# Read and assing all spreadsheets to an ob

for (i in 1:nrow(fs)) { 
  n <- paste0("d", stringr::str_replace(as.character(fs[i,"name"]), "_", ""))
  df <- readReplicas(as.character(fs[i, "id"]))
  assign(n, df) 
  }


ge <- purrr::map_df(fs$id, readReplicas)


readMetadatoVisita <- function(id){
  require(dplyr)
  require(googlesheets4)
  m <- read_sheet(ss=id, sheet = 'metadatoVisita', na = "NA")
  return(m)} 
  

m <- purrr::map_df(fs$id, readMetadatoVisita)

write_csv(g, here::here("/data/revision_siembras_all.csv"))
write_csv(m, here::here("/data/revision_siembras_all_md.csv"))





```



```{r}


unique(h$fieldworkers)


```






