---
title: "Untitled"
author: "Antonio J. Pérez-Luque"
date: "8/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("here")
# library("data.table")
library("stringr")
library("tidyverse")
```

Load specific functions 
```{r}
source(here::here('script/R','preparaHobo.R'))
source(here::here('script/R','validaHobo.R'))
```


```{r}
# Read files 
p <- ".*csv$"
f <- list.files(here::here("sensores/hoboRaw"), pattern= p, full.names = TRUE)

# PreparaHobo
df <- preparaHobo(f)

# Validate data
dfv <- validaHobo(df, vnameTemp='Temp')

dfv <- dfv %>% 
  filter(valid == 1) %>% 
  dplyr::select("Date","Time","Temp","sensorName")  
```




```{r}
# Get sensorNames from hobo 
sensores <- as.character(unique(dfv$sensorName))

# Read sensor correspondence
sensor <- read_csv(here::here("data", "sensorCorrespondence.csv")) 

sensor <- sensor %>% filter(sensorName %in% sensores) %>% dplyr::select(-date)
```


# Get climate statistics 
```{r}

temp <- dfv %>% 
  group_by(Date, sensorName) %>% 
  summarise(tmin = min(Temp),
            tmax = max(Temp),
            tmean = mean(Temp),
            amplitude = max(Temp) - min(Temp))

temp <- temp %>% inner_join(sensor, by="sensorName")


tempLoc <- temp %>% 
  group_by(microhabitat, loc, Date) %>% 
  summarise_at(c('tmax', 'tmin', 'tmean', 'amplitude'), mean, na.rm=TRUE)


tempLoc %>% ggplot(aes(y=tmean, x=Date)) + geom_point() + facet_grid(microhabitat~loc) 

```





```{r, eval=FALSE, echo=FALSE}

# Test 1 
# Inicio NA NA 

df <- as.data.frame(cbind(
  temp = c(1:13),
  BadBattery = c(NA,NA,NA,NA,NA,NA,NA,"Logged",NA,NA,NA,NA,NA),
  GoodBattery = c(NA,NA,NA,NA,NA,NA,NA,NA,NA,NA, "Logged",NA,NA)
))


df$cc <- ifelse(is.na(df$BadBat) & is.na(df$GoodBat), NA,
                ifelse(!is.na(df$BadBat), 'Bad', 'Good'))

df <- df %>% mutate(flag = na.locf0(cc)) 
          




  aux <- df %>% mutate(
    auxFlag = ifelse(is.na(BadBattery) & is.na(GoodBattery), NA, 
                      ifelse(!is.na(BadBattery), 'Bad', 'Good')),
    flag0 = zoo::na.locf0(auxFlag)) %>% 
    mutate(flag = ifelse(is.na(flag0), 'Good',flag0)) %>% 
    dplyr::select(-c(auxFlag, flag0))
  
  
  
   
# Test 2 
# Inicio NA Logged 

df <- as.data.frame(cbind(
  temp = c(1:13),
  BadBattery = c(NA,NA,NA,NA,NA,NA,NA,"Logged",NA,NA,NA,NA,NA),
  GoodBattery = c("Logged",NA,NA,NA,NA,NA,NA,NA,NA,NA, "Logged",NA,NA)
))


df$cc <- ifelse(is.na(df$BadBat) & is.na(df$GoodBat), NA,
                ifelse(!is.na(df$BadBat), 'Bad', 'Good'))

df <- df %>% mutate(flag = na.locf0(cc))
  
# Test 3 
# Inicio Logged NA

df <- as.data.frame(cbind(
  temp = c(1:13),
  BadBattery = c("Logged",NA,NA,NA,NA,NA,NA,"Logged",NA,NA,NA,NA,NA),
  GoodBattery = c(NA,NA,NA,"Logged",NA,NA,NA,NA,NA,NA, "Logged",NA,NA)
))


df$cc <- ifelse(is.na(df$BadBat) & is.na(df$GoodBat), NA,
                ifelse(!is.na(df$BadBat), 'Bad', 'Good'))

df <- df %>% mutate(flag = na.locf0(cc))
  


# OLD parte de la funcion valida Hobo 

  # aux <- df %>% mutate(
  #   bB = as.numeric(if_else(is.na(BadBattery), 0, -1)),
  #   gB = as.numeric(if_else(is.na(GoodBattery), 0, 1)),
  #   aux_flag = bB + gB,
  #   # https://stackoverflow.com/questions/20416046/filling-data-frame-with-previous-row-value 
  #   flag = ave(aux_flag, cumsum(aux_flag), FUN = function(x) x[x !=0])) %>% 
  #   dplyr::select(-c(bB,gB,aux_flag))
  # 


  # Validate temperature range (-20 to 70 C degree) in air. 
  # See http://www.onsetcomp.com/products/data-loggers/utbi-001
  validdf <- aux %>% 
    mutate(valid = if_else(
      .[[vnameTemp]] < -20, 0, if_else(.[[vnameTemp]] >= 70, 0, 1)
    )) 
  
  ## Delete first and last day 
  
  out <- validdf %>% 
    filter(.[[vnameDate]] != min(.[[vnameDate]])) %>% 
    filter(.[[vnameDate]] != max(.[[vnameDate]])) 
  
  return(out)
  
 

```
